feat: Initialize project and add new GitLab project integration
lemniscat-devops/lemniscat.plugin.gitlab pull request #1
Opened 2024-03-29 08:58 UTC by daviddubourg

2024-03-29 09:49 UTC, Ineaweb requested changes

2024-03-29 09:49 UTC, Ineaweb commented on pyproject.toml
> +description = "A runtime to provide product oriented in DevOps approach"
corriger la description

2024-03-29 09:49 UTC, Ineaweb commented on src/lemniscat/plugin/gitlab/gitLab.py
ajouter des logs de type DEBUG ?

2024-03-29 13:02 UTC, daviddubourg commented on src/lemniscat/plugin/gitlab/gitLab.py
oui, je le ferai

2024-04-03 09:46 UTC, Ineaweb approved these changes

2024-04-03 09:46 UTC, merged